# Generated by Django 4.2.7 on 2026-01-22 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_workoutvideo_day_number_workoutvideo_uploaded_via"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutvideo",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_videos",
                to="users.trainer",
            ),
        ),
    ]
