# Generated by Django 4.2.7 on 2026-02-02 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("gpay", "GPay"),
                            ("phonepe", "PhonePe"),
                            ("paytm", "Paytm"),
                            ("credit_card", "Credit Card"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "renewal_period",
                    models.IntegerField(
                        choices=[
                            (1, "1 Month"),
                            (2, "2 Months"),
                            (3, "3 Months"),
                            (6, "6 Months"),
                            (8, "8 Months"),
                            (12, "12 Months"),
                        ],
                        verbose_name="Renewal Period (Months)",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Transaction Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Receipt Number"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Discount Percentage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="users.userlogin",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "db_table": "payment_transaction",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
