# Generated by Django 4.2.7 on 2026-02-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_paymenttransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="payment_pin",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Payment PIN (Hashed)",
            ),
        ),
    ]
